version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
    networks:
        - djnet
  rabbitmq:
    image: rabbitmq:latest
    ports:
        - 5672:5672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    depends_on:
      - db
    networks:
        - djnet
  app:
    build: .
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
        - djnet
networks:
  djnet:
    driver: bridge