# Generated by Django 4.1.3 on 2022-11-03 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('description', models.CharField(max_length=256, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('description', models.CharField(max_length=256, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='сумма')),
                ('time', models.DateField(verbose_name='Время')),
                ('description', models.CharField(max_length=256, verbose_name='описание')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='api.category', verbose_name='категории')),
                ('organizations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='api.organization', verbose_name='организации')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзацкции',
            },
        ),
    ]
