# Generated by Django 4.1.3 on 2022-11-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='organizations',
            new_name='organization',
        ),
    ]
