# Generated by Django 4.1.3 on 2022-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction_user_alter_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default='2022-11-08 15:17:05.089046', verbose_name='Время'),
        ),
    ]
