# Generated by Django 4.1.3 on 2022-11-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default='2022-11-09 18:08:29.979582', verbose_name='Время'),
        ),
    ]
